routes/web.php
<?php

Route::get('/', 'Controller@index');
//Route::get('/offline.html', 'Controller@index');

Auth::routes();
Route::middleware('auth')->group(function () {
    Route::resource('categories', 'CategoriesController');
    Route::resource('items', 'ItemController');

    Route::get('/home', 'CategoriesController@index')->name('home');
});

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Category.
 *
 * @property int $id
 * @property string $name
 * @property string $image
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 *
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereImage($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Category whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Category extends Model
{
    protected $fillable = ['name', 'image'];
}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Auth;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('home', [
            'categories'     => Auth::user()->items->unique('category_id')->pluck('category'),
            'categories_all' => Category::all(),
        ]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param Category $category
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function show(Category $category, Request $request)
    {
        return view('category.show', [
            'category' => $category,
            'items'    => $request->user()->items()->where('category_id', $category->id)->orderBy('updated_at')->get(),
        ]);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param \Illuminate\Http\Request $request
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     *
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/category/show.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header d-flex justify-content-between">
                        <p class="m-2"><b>{{$category->name}}</b></p>
                        <button class="btn" data-toggle="collapse" data-target="#collapseExample" aria-expanded="false"
                                aria-controls="collapseExample">
                            add new item
                        </button>
                    </div>
                    <div class="collapse" id="collapseExample">
                        <form method="post" enctype="multipart/form-data" class="p-4 border border-success"
                              action="{{route('items.store')}}">
                            {{csrf_field()}}
                            <div class="form-group">
                                <label for="photo">Photo</label>
                                <input type="file" class="form-control-file" accept="image/jpeg" id="photo"
                                       name="photo" required>
                            </div>
                            <input type="hidden" value="{{$category->id}}" name="category_id"/>
                            <button type="submit" class="btn btn-success">Save</button>
                        </form>
                    </div>
                    <div class="card-body d-flex flex-column">
                        @foreach($items as $item)
                            <div class="card p-1 m-1">
                                <h5 class="text-center">
                                    Uses: <b>{{$item->usages()->count()}}</b>.
                                    Last at <b>{{$item->updated_at->format('d.m.Y H:i:s')}}</b>
                                </h5>
                                <img class="card-img-top" src="{{$item->image}}" alt="item">
                                <div class="card-body p-1">
                                    <div class="clearfix">
                                        <form action="{{route('items.destroy', $item)}}" method="post">
                                            {{method_field('delete')}}
                                            {{csrf_field()}}
                                            <button style="min-width: 85px" class="btn btn-outline-danger float-left"
                                                    type="submit">
                                                REMOVE
                                            </button>
                                        </form>
                                        <form action="{{route('items.update', $item)}}" method="post">
                                            {{method_field('put')}}
                                            {{csrf_field()}}
                                            <button style="min-width: 85px" class="btn btn-outline-success float-right">
                                                USE
                                            </button>
                                        </form>

                                    </div>
                                </div>
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection